FROM node:9-alpine as intermediate-build
MAINTAINER Yalcin Surkultay "yalcinsurkultay@gmail.com"

COPY ./client /app
WORKDIR /app

RUN yarn install && yarn build

FROM nginx:1.13.12-alpine as final-build
COPY --from=intermediate-build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
